news/urls.py
from django.urls import path
from .views import bbc,the_verge,vice,aljazeera_news

app_name='news'
urlpatterns=[
	path('',bbc,name='bbc-news'),
	path('verge/',the_verge,name='verge-news'),
	path('vice/',vice,name='vice-news'),
	path('aljazeera',aljazeera_news,name='aljazeera-news')
]

newsapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('news.urls')),
]

news/models.py
from django.db import models

# Create your models here.

news/views.py
from django.shortcuts import render
from newsapi import NewsApiClient


# Create your views here.

newsapi = NewsApiClient(api_key='ec84c3f1d9e8452b888ed528b2cc097b')





def bbc(request):	
	top_headlines = newsapi.get_top_headlines(sources='bbc-news')
	bbc_articles=top_headlines['articles']
	context={'item':bbc_articles}
	
	return render(request,'news/news.html',context)

def the_verge(request):
	verge_headlines=newsapi.get_top_headlines(sources='the-verge')
	verge_articles=verge_headlines['articles']
	context={'item':verge_articles}

	return render(request,'news/verge.html',context)

def vice(request):
	vice_headlines=newsapi.get_top_headlines(sources='vice-news')
	vice_articles=vice_headlines['articles']
	context={'item':vice_articles}

	return render(request,'news/vice.html',context)

def aljazeera_news(request):
	alj_headlines=newsapi.get_top_headlines(sources='al-jazeera-english')
	alj_articles=alj_headlines['articles']
	context={'item':alj_articles}

	return render(request,'news/aljazeera_news.html',context)

news/templates/news/aljazeera_news.html
{%extends 'base.html'%}
	
{%block content%}
<div class="container mt-3">
	
<div class="row">
	{%for i in item%}
  <div class="col-sm-4 py-2">
    <div class="card border-primary">
   	  <img class="card-img-top img-fluid" src="{{i.urlToImage}}" alt="Card image cap">	
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
				<p class="card-text mb-3">{{i.description}}</p>
				<a href="{{i.url}}"target='_blank' class="btn btn-dark">Read More</a>
      </div>

    </div>
  </div>
{%endfor%}
  </div>
  
</div>
<

{%endblock content%}

news/templates/news/news.html
{%extends 'base.html'%}
	
{%block content%}
<div class="container mt-3">
	
<div class="row">
	{%for i in item%}
  <div class="col-sm-4 py-2">
    <div class="card border-primary">
   	  <img class="card-img-top img-fluid" src="{{i.urlToImage}}" alt="Card image cap">	
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
				<p class="card-text mb-3">{{i.description}}</p>
				<a href="{{i.url}}"target='_blank' class="btn btn-dark">Read More</a>
      </div>

    </div>
  </div>
{%endfor%}
  </div>
  
</div>
<

{%endblock content%}

news/templates/news/verge.html
{%extends 'base.html'%}

{%block content%}
<div class="container mt-3">
	
<div class="row">
	{%for i in item%}
  <div class="col-sm-4 py-2">
    <div class="card border-primary">
   	  <img class="card-img-top img-fluid" src="{{i.urlToImage}}" alt="Card image cap">	
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
				<p class="card-text mb-3">{{i.description}}</p>
				<a href="{{i.url}}"target='_blank' class="btn btn-dark">Read More</a>
      </div>

    </div>
  </div>
{%endfor%}
  </div>
  
</div>
<

{%endblock content%}

<div class="container">
	
	{%for i in item%}
	    <div class="card" style="width: 20rem;">
		  <img class="card-img-top" src="{{i.urlToImage}}" alt="Card image cap">
			  <div class="card-body">
			    	<h5 class="card-title">{{i.author}}</h5>
			    	<p class="card-text">{{i.description}}</p>
			    	<!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
			  </div>
		</div>	
	{%endfor%}
</div>

news/templates/news/vice.html
{%extends 'base.html'%}
	
{%block content%}
<div class="container mt-3">
	
<div class="row">
	{%for i in item%}
  <div class="col-sm-4 py-2">
    <div class="card border-primary">
   	  <img class="card-img-top img-fluid" src="{{i.urlToImage}}" alt="Card image cap">	
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
				<p class="card-text mb-3">{{i.description}}</p>
				<a href="{{i.url}}"target='_blank' class="btn btn-dark">Read More</a>
      </div>

    </div>
  </div>
{%endfor%}
  </div>
  
</div>
<

{%endblock content%}

<div class="container">
	
	{%for i in item%}
	    <div class="card" style="width: 20rem;">
		  <img class="card-img-top" src="{{i.urlToImage}}" alt="Card image cap">
			  <div class="card-body">
			    	<h5 class="card-title">{{i.author}}</h5>
			    	<p class="card-text">{{i.description}}</p>
			    	<!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
			  </div>
		</div>	
	{%endfor%}
</div>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	
  {%include 'nav.html'%}
 
	{%block content%}	
	
	
		
		


	{%endblock content%}



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark ">
    <div class="container">  
      <a class="navbar-brand" href="#">Daily News</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:bbc-news' %}">BBC</a> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:verge-news' %}">VERGE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:vice-news' %}">VICE</a>
          </li>
          <li>
            <a class="nav-link" href="{%url 'news:aljazeera-news' %}">Al-Jazeera</a>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
</nav>